---
title: "simpleRegress"
author: "Davy D"
date: "Spring 2024"
output: html_document
---
## Compare all models 
Predict LENGTH based on the variables other than LENGTH. Then order them from worst to best by its value of Adjusted-Rsquared (bigger is better), or by RSE (residual standard error) where smaller is better.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

## Model LENGTH ~ NECK  this is an example  

```{r}
simp <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(simp)
summary.lm(simp)
```


```{r}
simpAGE <- lm(LENGTH~AGE,data=bears)
plot(LENGTH~AGE,data=bears)
abline(simpAGE)
summary.lm(simpAGE)
```





```{r}
simpSEX <- lm(LENGTH~SEX,data=bears)
plot(LENGTH~SEX,data=bears)
abline(simpSEX)
summary.lm(simpSEX)
```
```{r}
simpMONTH <- lm(LENGTH~MONTH,data=bears)
plot(LENGTH~MONTH,data=bears)
abline(simpMONTH)
summary.lm(simpMONTH)
```



```{r}
simpHEADLEN <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(simpHEADLEN)
summary.lm(simpHEADLEN)
```
```{r}
simpHEADWTH <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(simpHEADWTH)
summary.lm(simpHEADWTH)
```

```{r}
simpCHEST <- lm(LENGTH~CHEST,data=bears)
plot(LENGTH~CHEST,data=bears)
abline(simpCHEST)
summary.lm(simpCHEST)
```

```{r}
simpWEIGHT <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(simpWEIGHT)
summary.lm(simpWEIGHT)
```


The best simple model so far is length~  

